name: Goblins-And-Kittens

on:
  push:
    branches:
      - speed_mod

jobs:
  build:
    name: Build .exe (Python ${{ matrix.python-version }})
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade `pip`
        run: python -m pip install --upgrade pip

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Display Local Files
        run: dir
        shell: cmd

      - name: Make app.exe
        run: pyinstaller --onefile --windowed --add-data="sprites/castle.png;." --add-data="sprites/Mosquito/Mosquito Flying Pose.png;." --add-data="sprites/Goblin/$Goblin.png;." --add-data="sprites/Goblin/Goblin Dying Pose.png;." --add-data="sprites/Evil Head/Evil Head Biting.png;." --add-data="sprites/Evil Skull/Skull Rotten Biting.png;." --add-data="sprites/CART_2.png;." --add-data="sprites/Cats/Black.png;." --add-data="sprites/Cats/Orange.png;." --add-data="sprites/Cats/Yellow.png;." --add-data="sprites/BG112A_W.png;." GameOfLife.py

      - name: Upload .exe
        uses: actions/upload-artifact@v2
        with:
          name: Goblins-And-Kittens
          path: dist/Goblins-And-Kittens.exe

  upload-artifacts:
    name: Upload Artifact
    needs: build
    runs-on: windows-latest

    steps:
      - name: Display Local Files
        run: dir
        shell: cmd

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        id: download
        with:
          name: Goblins-And-Kittens
          path: dist/Goblins-And-Kittens.exe

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
